# Generated by Django 3.0.6 on 2020-06-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_author', models.CharField(max_length=10)),
                ('blog_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created')),
                ('blog', models.CharField(max_length=200)),
            ],
        ),
    ]
