# Generated by Django 3.0.6 on 2020-06-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog',
            field=models.TextField(max_length=200),
        ),
    ]
